[error] java.lang.ExceptionInInitializerError
[error] 	at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
[error] 	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[error] 	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
[error] 	at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
[error] 	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
[error] 	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
[error] 	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
[error] 	at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
[error] 	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:95)
[error] 	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
[error] 	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
[error] 	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
[error] 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
[error] 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
[error] 	at org.mockito.Mockito.mock(Mockito.java:1285)
[error] 	at org.mockito.Mockito.mock(Mockito.java:1163)
[error] 	at org.scalatestplus.mockito.MockitoSugar.mock(MockitoSugar.scala:73)
[error] 	at org.scalatestplus.mockito.MockitoSugar.mock$(MockitoSugar.scala:72)
[error] 	at org.scalatestplus.mockito.MockitoSugar$.mock(MockitoSugar.scala:155)
[error] 	at com.knoldus.services.HealthCheckServiceTest.<init>(HealthCheckServiceTest.scala:16)
[error] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[error] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[error] 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[error] 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306)
[error] 	at java.base/java.lang.Class.newInstance(Class.java:684)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:450)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:140)
[error] 	at sbt.TestRunner.run(TestFramework.scala:155)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:318)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:278)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:318)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:318)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:330)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:435)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @d1d4088
[error] 	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
[error] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
[error] 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
[error] 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:201)
[error] 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:195)
[error] 	at org.mockito.cglib.core.ReflectUtils$2.run(ReflectUtils.java:57)
[error] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
[error] 	at org.mockito.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:47)
[error] 	at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
[error] 	at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
[error] 	at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
[error] 	at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
[error] 	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
[error] 	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
[error] 	at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
[error] 	at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
[error] 	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxyClass(ClassImposterizer.java:95)
[error] 	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:57)
[error] 	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
[error] 	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
[error] 	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
[error] 	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
[error] 	at org.mockito.Mockito.mock(Mockito.java:1285)
[error] 	at org.mockito.Mockito.mock(Mockito.java:1163)
[error] 	at org.scalatestplus.mockito.MockitoSugar.mock(MockitoSugar.scala:73)
[error] 	at org.scalatestplus.mockito.MockitoSugar.mock$(MockitoSugar.scala:72)
[error] 	at org.scalatestplus.mockito.MockitoSugar$.mock(MockitoSugar.scala:155)
[error] 	at com.knoldus.services.HealthCheckServiceTest.<init>(HealthCheckServiceTest.scala:16)
[error] 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
[error] 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[error] 	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
[error] 	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:306)
[error] 	at java.base/java.lang.Class.newInstance(Class.java:684)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:450)
[error] 	at sbt.TestRunner.runTest$1(TestFramework.scala:140)
[error] 	at sbt.TestRunner.run(TestFramework.scala:155)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:318)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:278)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:318)
[error] 	at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:318)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:330)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:435)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[error] 	at java.base/java.lang.Thread.run(Thread.java:1589)
[error] (Test / executeTests) java.lang.ExceptionInInitializerError
